//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BanBanhEntities : DbContext
    {
        public BanBanhEntities()
            : base("name=BanBanhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDH> CTDHs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        [DbFunction("BanBanhEntities", "f_CartUs")]
        public virtual IQueryable<f_CartUs_Result> f_CartUs(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_CartUs_Result>("[BanBanhEntities].[f_CartUs](@Userid)", useridParameter);
        }
    
        [DbFunction("BanBanhEntities", "f_slBan")]
        public virtual IQueryable<f_slBan_Result> f_slBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_slBan_Result>("[BanBanhEntities].[f_slBan]()");
        }
    
        [DbFunction("BanBanhEntities", "f_Sptheo_Loai")]
        public virtual IQueryable<f_Sptheo_Loai_Result> f_Sptheo_Loai(string mALOAISP)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_Sptheo_Loai_Result>("[BanBanhEntities].[f_Sptheo_Loai](@MALOAISP)", mALOAISPParameter);
        }
    
        [DbFunction("BanBanhEntities", "f_timUser_SDT")]
        public virtual IQueryable<f_timUser_SDT_Result> f_timUser_SDT(Nullable<int> sDT)
        {
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_timUser_SDT_Result>("[BanBanhEntities].[f_timUser_SDT](@SDT)", sDTParameter);
        }
    
        [DbFunction("BanBanhEntities", "func_LayIdUser")]
        public virtual IQueryable<func_LayIdUser_Result> func_LayIdUser(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_LayIdUser_Result>("[BanBanhEntities].[func_LayIdUser](@id)", idParameter);
        }
    
        public virtual int PSignIn(string name, string pass, string mail, string phone, string add)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PSignIn", nameParameter, passParameter, mailParameter, phoneParameter, addParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_CapNhatCTDH(string sODH, string mASP, Nullable<int> sL)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_CapNhatCTDH", sODHParameter, mASPParameter, sLParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_CapNhatCTDH(string sODH, string mASP, Nullable<int> sL, MergeOption mergeOption)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_CapNhatCTDH", mergeOption, sODHParameter, mASPParameter, sLParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_CapNhatDH(string sODH, string uSER_ID, Nullable<System.DateTime> nGAYDAT, Nullable<System.DateTime> nGAYGIAO)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var nGAYDATParameter = nGAYDAT.HasValue ?
                new ObjectParameter("NGAYDAT", nGAYDAT) :
                new ObjectParameter("NGAYDAT", typeof(System.DateTime));
    
            var nGAYGIAOParameter = nGAYGIAO.HasValue ?
                new ObjectParameter("NGAYGIAO", nGAYGIAO) :
                new ObjectParameter("NGAYGIAO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_CapNhatDH", sODHParameter, uSER_IDParameter, nGAYDATParameter, nGAYGIAOParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_CapNhatDH(string sODH, string uSER_ID, Nullable<System.DateTime> nGAYDAT, Nullable<System.DateTime> nGAYGIAO, MergeOption mergeOption)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var nGAYDATParameter = nGAYDAT.HasValue ?
                new ObjectParameter("NGAYDAT", nGAYDAT) :
                new ObjectParameter("NGAYDAT", typeof(System.DateTime));
    
            var nGAYGIAOParameter = nGAYGIAO.HasValue ?
                new ObjectParameter("NGAYGIAO", nGAYGIAO) :
                new ObjectParameter("NGAYGIAO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_CapNhatDH", mergeOption, sODHParameter, uSER_IDParameter, nGAYDATParameter, nGAYGIAOParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_CapNhatLSP(string mALOAISP, string tENLOAISP)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var tENLOAISPParameter = tENLOAISP != null ?
                new ObjectParameter("TENLOAISP", tENLOAISP) :
                new ObjectParameter("TENLOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_CapNhatLSP", mALOAISPParameter, tENLOAISPParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_CapNhatLSP(string mALOAISP, string tENLOAISP, MergeOption mergeOption)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var tENLOAISPParameter = tENLOAISP != null ?
                new ObjectParameter("TENLOAISP", tENLOAISP) :
                new ObjectParameter("TENLOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_CapNhatLSP", mergeOption, mALOAISPParameter, tENLOAISPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_CapNhatSP(string mASP, string tENSP, string dVT, string nOISX, Nullable<int> gIA, string mOTA, Nullable<System.DateTime> nGAYCAPNHAT, string mALOAISP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var nOISXParameter = nOISX != null ?
                new ObjectParameter("NOISX", nOISX) :
                new ObjectParameter("NOISX", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(int));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var nGAYCAPNHATParameter = nGAYCAPNHAT.HasValue ?
                new ObjectParameter("NGAYCAPNHAT", nGAYCAPNHAT) :
                new ObjectParameter("NGAYCAPNHAT", typeof(System.DateTime));
    
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_CapNhatSP", mASPParameter, tENSPParameter, dVTParameter, nOISXParameter, gIAParameter, mOTAParameter, nGAYCAPNHATParameter, mALOAISPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_CapNhatSP(string mASP, string tENSP, string dVT, string nOISX, Nullable<int> gIA, string mOTA, Nullable<System.DateTime> nGAYCAPNHAT, string mALOAISP, MergeOption mergeOption)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var nOISXParameter = nOISX != null ?
                new ObjectParameter("NOISX", nOISX) :
                new ObjectParameter("NOISX", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(int));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var nGAYCAPNHATParameter = nGAYCAPNHAT.HasValue ?
                new ObjectParameter("NGAYCAPNHAT", nGAYCAPNHAT) :
                new ObjectParameter("NGAYCAPNHAT", typeof(System.DateTime));
    
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_CapNhatSP", mergeOption, mASPParameter, tENSPParameter, dVTParameter, nOISXParameter, gIAParameter, mOTAParameter, nGAYCAPNHATParameter, mALOAISPParameter);
        }
    
        public virtual ObjectResult<USER> sp_CapNhatUser(string uSER_ID, string uSER_NAME, string pASSWORD, string eMAIL, string sODT, string dCHI)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sODTParameter = sODT != null ?
                new ObjectParameter("SODT", sODT) :
                new ObjectParameter("SODT", typeof(string));
    
            var dCHIParameter = dCHI != null ?
                new ObjectParameter("DCHI", dCHI) :
                new ObjectParameter("DCHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_CapNhatUser", uSER_IDParameter, uSER_NAMEParameter, pASSWORDParameter, eMAILParameter, sODTParameter, dCHIParameter);
        }
    
        public virtual ObjectResult<USER> sp_CapNhatUser(string uSER_ID, string uSER_NAME, string pASSWORD, string eMAIL, string sODT, string dCHI, MergeOption mergeOption)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sODTParameter = sODT != null ?
                new ObjectParameter("SODT", sODT) :
                new ObjectParameter("SODT", typeof(string));
    
            var dCHIParameter = dCHI != null ?
                new ObjectParameter("DCHI", dCHI) :
                new ObjectParameter("DCHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_CapNhatUser", mergeOption, uSER_IDParameter, uSER_NAMEParameter, pASSWORDParameter, eMAILParameter, sODTParameter, dCHIParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_LayCTDH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_LayCTDH");
        }
    
        public virtual ObjectResult<CTDH> sp_LayCTDH(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_LayCTDH", mergeOption);
        }
    
        public virtual ObjectResult<DONHANG> sp_LayDH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_LayDH");
        }
    
        public virtual ObjectResult<DONHANG> sp_LayDH(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_LayDH", mergeOption);
        }
    
        public virtual ObjectResult<CTDH> sp_LayidCTHD(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_LayidCTHD", idParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_LayidCTHD(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_LayidCTHD", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_LayidDH(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_LayidDH", idParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_LayidDH(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_LayidDH", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_LayidLSP(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_LayidLSP", idParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_LayidLSP(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_LayidLSP", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_LayidSP(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_LayidSP", idParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_LayidSP(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_LayidSP", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<USER> sp_LayidUser(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_LayidUser", idParameter);
        }
    
        public virtual ObjectResult<USER> sp_LayidUser(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_LayidUser", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_LayLSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_LayLSP");
        }
    
        public virtual ObjectResult<LOAISP> sp_LayLSP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_LayLSP", mergeOption);
        }
    
        public virtual ObjectResult<SANPHAM> sp_LaySP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_LaySP");
        }
    
        public virtual ObjectResult<SANPHAM> sp_LaySP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_LaySP", mergeOption);
        }
    
        public virtual ObjectResult<USER> sp_LayUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_LayUser");
        }
    
        public virtual ObjectResult<USER> sp_LayUser(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_LayUser", mergeOption);
        }
    
        public virtual ObjectResult<sp_maxGia_Result> sp_maxGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_maxGia_Result>("sp_maxGia");
        }
    
        public virtual ObjectResult<sp_minGia_Result> sp_minGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_minGia_Result>("sp_minGia");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_ThemCTDH(string uSER_ID, string mASP, Nullable<int> sL)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_ThemCTDH", uSER_IDParameter, mASPParameter, sLParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_ThemCTDH(string uSER_ID, string mASP, Nullable<int> sL, MergeOption mergeOption)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_ThemCTDH", mergeOption, uSER_IDParameter, mASPParameter, sLParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_ThemDH(string uSER_ID)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_ThemDH", uSER_IDParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_ThemDH(string uSER_ID, MergeOption mergeOption)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_ThemDH", mergeOption, uSER_IDParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_ThemLSP(string mALOAISP, string tENLOAISP)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var tENLOAISPParameter = tENLOAISP != null ?
                new ObjectParameter("TENLOAISP", tENLOAISP) :
                new ObjectParameter("TENLOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_ThemLSP", mALOAISPParameter, tENLOAISPParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_ThemLSP(string mALOAISP, string tENLOAISP, MergeOption mergeOption)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var tENLOAISPParameter = tENLOAISP != null ?
                new ObjectParameter("TENLOAISP", tENLOAISP) :
                new ObjectParameter("TENLOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_ThemLSP", mergeOption, mALOAISPParameter, tENLOAISPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_ThemSP(string tENSP, string dVT, string nOISX, Nullable<int> gIA, string mOTA, string mALOAISP, string hINH)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var nOISXParameter = nOISX != null ?
                new ObjectParameter("NOISX", nOISX) :
                new ObjectParameter("NOISX", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(int));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var hINHParameter = hINH != null ?
                new ObjectParameter("HINH", hINH) :
                new ObjectParameter("HINH", "helo");
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_ThemSP", tENSPParameter, dVTParameter, nOISXParameter, gIAParameter, mOTAParameter, mALOAISPParameter, hINHParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_ThemSP(string tENSP, string dVT, string nOISX, Nullable<int> gIA, string mOTA, string mALOAISP, string hINH, MergeOption mergeOption)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var nOISXParameter = nOISX != null ?
                new ObjectParameter("NOISX", nOISX) :
                new ObjectParameter("NOISX", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(int));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            var hINHParameter = hINH != null ?
                new ObjectParameter("HINH", hINH) :
                new ObjectParameter("HINH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_ThemSP", mergeOption, tENSPParameter, dVTParameter, nOISXParameter, gIAParameter, mOTAParameter, mALOAISPParameter, hINHParameter);
        }
    
        public virtual ObjectResult<USER> sp_ThemUser(string uSER_NAME, string pASSWORD, string eMAIL, string sODT, string dCHI)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sODTParameter = sODT != null ?
                new ObjectParameter("SODT", sODT) :
                new ObjectParameter("SODT", typeof(string));
    
            var dCHIParameter = dCHI != null ?
                new ObjectParameter("DCHI", dCHI) :
                new ObjectParameter("DCHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_ThemUser", uSER_NAMEParameter, pASSWORDParameter, eMAILParameter, sODTParameter, dCHIParameter);
        }
    
        public virtual ObjectResult<USER> sp_ThemUser(string uSER_NAME, string pASSWORD, string eMAIL, string sODT, string dCHI, MergeOption mergeOption)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var sODTParameter = sODT != null ?
                new ObjectParameter("SODT", sODT) :
                new ObjectParameter("SODT", typeof(string));
    
            var dCHIParameter = dCHI != null ?
                new ObjectParameter("DCHI", dCHI) :
                new ObjectParameter("DCHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_ThemUser", mergeOption, uSER_NAMEParameter, pASSWORDParameter, eMAILParameter, sODTParameter, dCHIParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<CTDH> sp_XoaCTDH(string sODH)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_XoaCTDH", sODHParameter);
        }
    
        public virtual ObjectResult<CTDH> sp_XoaCTDH(string sODH, MergeOption mergeOption)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTDH>("sp_XoaCTDH", mergeOption, sODHParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_XoaDH(string sODH)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_XoaDH", sODHParameter);
        }
    
        public virtual ObjectResult<DONHANG> sp_XoaDH(string sODH, MergeOption mergeOption)
        {
            var sODHParameter = sODH != null ?
                new ObjectParameter("SODH", sODH) :
                new ObjectParameter("SODH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DONHANG>("sp_XoaDH", mergeOption, sODHParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_XoaLSP(string mALOAISP)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_XoaLSP", mALOAISPParameter);
        }
    
        public virtual ObjectResult<LOAISP> sp_XoaLSP(string mALOAISP, MergeOption mergeOption)
        {
            var mALOAISPParameter = mALOAISP != null ?
                new ObjectParameter("MALOAISP", mALOAISP) :
                new ObjectParameter("MALOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAISP>("sp_XoaLSP", mergeOption, mALOAISPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_XoaSP(string mASP)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_XoaSP", mASPParameter);
        }
    
        public virtual ObjectResult<SANPHAM> sp_XoaSP(string mASP, MergeOption mergeOption)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SANPHAM>("sp_XoaSP", mergeOption, mASPParameter);
        }
    
        public virtual ObjectResult<USER> sp_XoaUser(string uSER_ID)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_XoaUser", uSER_IDParameter);
        }
    
        public virtual ObjectResult<USER> sp_XoaUser(string uSER_ID, MergeOption mergeOption)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USER>("sp_XoaUser", mergeOption, uSER_IDParameter);
        }
    }
}
