//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDH
    {
        public string SODH { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
