//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDHs = new HashSet<CTDH>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string DVT { get; set; }
        public string NOISX { get; set; }
        public Nullable<int> GIA { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public string MALOAISP { get; set; }
        public string HINH { get; set; }

        public System.Web.HttpPostedFileBase filename { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
